/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Boat(props) {

    const boat = useRef()


    useFrame((state, delta)=> {
        const angle = state.clock.elapsedTime

        group.current.position.y = (Math.sin(angle) / 60) 
        group.current.rotation.z = (Math.sin(angle) / 30) 
    })

  const group = useRef()
  const { nodes, materials } = useGLTF('./boat.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
        <mesh geometry={nodes.boat_large_8angles.geometry} material={materials.wood} position={[-0.7, 1.68, 3.1]} scale={0.3} rotation-y={Math.PI/2 * 0.8} />
    </group>
  )
}

useGLTF.preload('./boat.gltf')