/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
import React, { useRef } from 'react'
import { useGLTF, 

 } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/rocks-forrest/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
        <mesh 
            geometry={nodes.rocksA_forest.geometry} 
            material={materials['Stone.007']} 
            rotation={[Math.PI / 2, 0, 2.7,]} 
            position={[-2.6,1.9,9]}
            scale={0.25} 
        />
        {/* <mesh 
            geometry={nodes.rocksA_forest.geometry} 
            material={materials['Stone.007']} 
            rotation={[Math.PI / 2, 0, 2.7,]} 
            position={[-2.4,1.9,7.7]}
            scale={0.25} 
        /> */}
    </group>
  )
}

useGLTF.preload('https://vazxmixjsiawhamofees.supabase.co/storage/v1/object/public/models/rocks-forrest/model.gltf')